name: "Bug"
description: "機能が設計通りに動作しない問題を報告"
title: "[Bug] "
labels: ["type/bug", "area/server", "need/triage"]
body:
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "どのような不具合なのか、簡潔な概要"
      placeholder: |
        「いいね」ボタンを連打するとカウントがマイナスになる

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "どのように動作することを期待していたか"
      placeholder: |
        連打してもAPIリクエストはデバウンスされ、正しいカウントが表示される

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "実際の動作はどうか"
      placeholder: |
        APIエラー(429 Too Many Requests)が返り、UI上のカウントがおかしくなる

  - type: textarea
    id: reproduction-info
    attributes:
      label: "Reproduction"
      description: "この不具合を再現するための条件や手順"
      placeholder: |
        条件:
          - ネットワーク速度: 低速 (3G)
        手順:
          1. 記事ページを開く
          2. いいねボタンを1秒間に5回クリックする
          3. カウント表示がズレる

  - type: textarea
    id: suggested-fix
    attributes:
      label: "Suggested Fix"
      description: "この不具合に対する推奨する解決策（あれば）"
      placeholder: |
        lodash.debounce を使ってクリックイベントを制御する
        API通信中はボタンをdisableにする

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "ログ、スクリーンショット、環境差分など"
      placeholder: |
        PC (Chrome) の検証ツールで確認。

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "関連情報や関連issue等あれば"
      placeholder: |
        - #1234
        - traP-jp/plutus#123456
